apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-apps-qa
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: prod
  source:
    # path: apps/2048-game/kustomized_helm/overlays/qa
    path: apps/infra/prod
    repoURL: https://github.com/knkarthik/argo-test.git
    targetRevision: HEAD
    # plugin:
    #   name: kustomized-helm
