apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: prod
  source:
    path: prod
    repoURL: https://github.com/knkarthik/argo-test.git
    targetRevision: HEAD
