apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-qa
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 2048-game-qa
    name: in-cluster
  project: qa
  source:
    # path: apps/2048-game/kustomized_helm/overlays/qa
    path: apps/infra/ingress-nginx/overlays/qa
    repoURL: https://github.com/knkarthik/argo-test.git
    targetRevision: HEAD
    plugin:
      name: kustomized-helm
